# .github/workflows/metrics.yml
name: GitHub Metrics

on:
  schedule:
    - cron: "0 1 * * *"   # Every day at 1AM UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_lines: yes
